routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => config('app.prefix_folder')], function () {

    Route::get('/', function () {
        return redirect()->route('admin.index');
    });

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('main', function () {
            return redirect()->route('admin.categories.index');
        })->name('index');

        Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {

            Route::get('/', [\App\Http\Controllers\Admin\CategoryController::class, 'index'])->name('index');
            Route::get('set', [\App\Http\Controllers\Admin\CategoryController::class, 'set'])->name('set');
            Route::get('remove', [\App\Http\Controllers\Admin\CategoryController::class, 'remove'])->name('remove');

        });
    });

});

resources/views/admin/partials/categories_list.blade.php
<div class="feed" data-category-feed="{{ $feed }}" id="feed-{{ $feed }}" style="display:none;">
    @for($i = 0; $i < 3; $i++)
        <div class="d-flex mr-3" data-row="{{ $i }}">
            @foreach($categories as $parent_id => $items)
                @if($i == 0 && $parent_id != null)
                    @continue
                @endif
                <ul class="list-group"
                    @if($i != 0) style="display:none;" @endif
                    data-feed="{{ $feed }}" data-row="{{ $i }}"
                    id="row-{{ $i }}-{{ $feed }}-{{ $parent_id }}">
                    @foreach($items as $category)
                        <li class="list-group-item"
                            data-feed="{{ $feed }}" data-id="{{ $category->id }}"
                            data-target="row-{{ $i + 1 }}-{{ $feed }}-{{ $category->id }}"
                            data-row="{{ $i }}">
                            {{ $category->feed_name }}
                            @if(!isset($categories[$category->id]))
                                <div class="mt-1">
                                    <small class="text-secondary cat_name" data-cs
                                           @if($category->category == null)
                                           style="display:none;"
                                           @else
                                           style="display:block;"
                                        @endif
                                    >
                                        {{ $category->category->description->name ?? '' }}
                                    </small>

                                    <small class="text-danger" data-ns
                                           @if($category->category != null)
                                           style="display:none;"
                                           @else
                                           style="display:block;"
                                        @endif
                                    >
                                        Категория не задана
                                    </small>

                                    <div class="mt-1">
                                        <div data-cs
                                             @if($category->category == null)
                                             style="display:none;"
                                            @endif
                                        >
                                            <small class="link-primary"
                                                   data-val="{{ $category->category_id }}"
                                                   data-change="{{ $category->id }}">
                                                Изменить
                                            </small>
                                            <small class="link-danger"
                                                   data-remove="{{ $category->id }}">
                                                Удалить
                                            </small>
                                        </div>
                                        <div data-ns
                                             @if($category->category != null)
                                             style="display:none;"
                                            @endif
                                        >
                                            <small class="link-primary"
                                                   data-val="{{ $category->category_id }}"
                                                   data-change="{{ $category->id }}">
                                                Задать категорию
                                            </small>
                                        </div>
                                        <div class="mt-1 cat-edit" style="display:none;">
                                            <select></select>
                                            <button class="btn btn-sm btn-primary" btn-save>
                                                Сохранить
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            @endif
                        </li>
                    @endforeach
                </ul>
            @endforeach
        </div>
    @endfor
</div>

resources/views/admin/partials/categories_scripts.blade.php
<script>
    $(function () {

        $('[data-open-feed]').click(function () {

            $('.feed').hide();
            $('#' + $(this).data('target-feed')).show();

            $('[data-open-feed]').removeClass('active');
            $(this).addClass('active');

        });


        $('[data-target]').click(function () {

            var row = $(this).data('row');

            $('.list-group[data-row]').filter(function () {
                return $(this).data('row') > row;
            }).hide();
            $('#' + $(this).data('target')).show();

            $('.list-group-item[data-row=' + (row) + ']').removeClass('active');

            if ($(this).find('[data-change]').length == 0)
                $(this).addClass('active');

        });

        $('[data-remove]').click(function () {
            var that = $(this);
            $.ajax({
                url: '{{ route('admin.categories.remove') }}',
                data: {
                    id: that.data('remove'),
                },
            });

            var item = that.parents('li');
            item.find('[data-cs]').hide();
            item.find('[data-ns]').show();
        });

        $('[data-change]').click(function () {
            var item = $(this).parents('li');
            item.find('.cat-edit').show();
            item.find('[data-cs], [data-ns]').hide();

            item.find('select').html(
                $('#local-categories-list').html()
            ).val(
                $(this).data('val')
            ).select2();
        });

        $('[btn-save]').click(function () {
            var that = $(this);
            var item = that.parents('li');
            var val = item.find('select').val();

            $.ajax({
                url: '{{ route('admin.categories.set') }}',
                data: {
                    id: item.find('[data-change]').data('change'),
                    value: val,
                },
            });

            item.find('.cat_name').text(
                $('#local-categories-list option[value="' + val + '"]').data('short')
            );
            item.find('[data-cs]').show();
            item.find('.cat-edit').hide();
            item.find('[data-change]').data('val', val);
        });

        $('[select2]').select2();

    });
</script>


<style>
    .feed {
        display: flex;
        flex-direction: row;
    }

    [data-row] {
        display: flex;
        flex-direction: column;
    }

    .mr-3 {
        margin-right: 10px;
    }

    [data-remove], [data-change] {
        cursor: pointer;
    }

    .select2-container {
        width: 270px !important;
    }

    .select2-selection, .select2-results__option {
        font-size: 14px;
    }

    [data-target-feed], [data-target] {
        cursor: pointer;
    }
</style>

resources/views/admin/partials/local_category.blade.php
<li class="list-group-item">
    @isset($listCategories[$category->category_id])
        <a data-bs-toggle="collapse" href="#cat-{{ $category->category_id }}" role="button"
           aria-expanded="false" aria-controls="cat-{{ $category->category_id }}">
            {{ $category->description->name ?? '?' }}
        </a>
    @else
        {{ $category->description->name ?? '?' }}
    @endisset

    @isset($listCategories[$category->category_id])
        <ul class="collapse list-group" id="cat-{{ $category->category_id }}">
            @foreach($listCategories[$category->category_id]->sortBy('sort_order') as $subCat)
                @include('admin.partials.local_category', ['category' => $subCat])
            @endforeach
        </ul>
    @endisset
</li>